# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v3.12.0"
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.2"
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/psf/black
    rev: "24.4.0"
    hooks:
      - id: black
        args: [--preview]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        types: [javascript]
        additional_dependencies:
          [
            "globals@13.21.0",
            "eslint@8.51.0",
            "@eslint/js",
            "eslint-config-prettier@9.0.0",
          ]
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--max-line-length", "99"]
