name: Update Site
on:
  workflow_dispatch:

jobs:
  generate:
    name: Update Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data_update/requirements.txt
      - name: Run Update
        run: |
          python -m data_update
        env:
          GDRIVE_SECRET: ${{ secrets.GDRIVE_SECRET }}
          GPHOTOS_SECRET: ${{ secrets.GPHOTOS_SECRET }}
          GPHOTOS_SECRET_STORAGE: ${{ secrets.GPHOTOS_SECRET_STORAGE }}
          FTP_SECRET: ${{ secrets.FTP_SECRET }}
