name: Update Site
on:
  workflow_dispatch:
    inputs:
      update_media:
        description: "Pull images/videos"
        required: true
        default: "true"

jobs:
  generate:
    name: Update Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v6.0.1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.2
      - name: Install dependencies
        run: |
          poetry install --without dev
      - name: Run Update
        run: |
          poetry run python -m data_update
        env:
          GDRIVE_SECRET: ${{ secrets.GDRIVE_SECRET }}
          GDRIVE_VIDEOS_SECRET: ${{ secrets.GDRIVE_VIDEOS_SECRET }}
          GPHOTOS_SECRET: ${{ secrets.GPHOTOS_SECRET }}
          GPHOTOS_SECRET_STORAGE: ${{ secrets.GPHOTOS_SECRET_STORAGE }}
          FTP_SECRET: ${{ secrets.FTP_SECRET }}
          UPDATE_MEDIA: ${{ inputs.update_media }}
      - name: push to github pages
        id: push_directory
        uses: PaulKlinger/github-action-push-to-another-repository@54421fde4f1675bdd43f562435267207398f4394
        env:
          SSH_DEPLOY_KEY: ${{ secrets.GHPAGES_DEPLOY_KEY }}
        with:
          source-directory: web
          target-directory: contents/ceramics
          destination-github-username: "PaulKlinger"
          destination-repository-name: "paulklinger.github.io"
          user-email: klinger.paul+automation@gmail.com
          commit-message: update ceramics
          target-branch: master
