name: Update Site
on:
  workflow_dispatch:

jobs:
  generate:
    name: Update Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data_update/requirements.txt
      - name: Run Update
        run: |
          python -m data_update
        env:
          GDRIVE_SECRET: ${{ secrets.GDRIVE_SECRET }}
          GDRIVE_VIDEOS_SECRET: ${{ secrets.GDRIVE_VIDEOS_SECRET }}
          GPHOTOS_SECRET: ${{ secrets.GPHOTOS_SECRET }}
          GPHOTOS_SECRET_STORAGE: ${{ secrets.GPHOTOS_SECRET_STORAGE }}
          FTP_SECRET: ${{ secrets.FTP_SECRET }}
      - name: push to github pages
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.GHPAGES_DEPLOY_KEY }}
        with:
          source-directory: web
          target-directory: ceramics
          destination-github-username: "PaulKlinger"
          destination-repository-name: "paulklinger.github.io"
          user-email: klinger.paul+automation@gmail.com
          commit-message: update ceramics
          target-branch: master
